/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package bayarzakat;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.Dimension;
import java.awt.Toolkit;
/**
 *
 * @author USER
 */

public class detildata extends javax.swing.JFrame {

    public static Connection conn = null;
    public static Statement stmt = null;
    public static final String USER = "root";
    public static final String PASS = "";
    /**
     * Creates new form detildata
     */
    public detildata() {
         initComponents();
         Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();
        // membuat titik x dan y
        int x = layar.width / 2  - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;
        this.setLocation(x, y);
         tampil();
    }
    
    public void tampil() {
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost/dompet_zakat", USER, PASS);
            stmt = conn.createStatement();

            DefaultTableModel tm = (DefaultTableModel) detilmuzaki.getModel();
            tm.setRowCount(0);
            ResultSet result = null;
            result = stmt.executeQuery("SELECT `transaksi_zakat`.id_zakat,`nama_muzaki`,`no_telepon`,`alamat`,`email`, `harta_tab` FROM `muzaki` INNER JOIN `transaksi_zakat` ON (`muzaki`.id = `transaksi_zakat`.id_muzaki) INNER JOIN `zakat_harta` ON (`transaksi_zakat`.id_zakat = `zakat_harta`.id)");
            while (result.next()) {
                Object o[] = {result.getString("id_zakat"), result.getString("nama_muzaki"), result.getString("no_telepon"), result.getString("alamat"),result.getString("email")};
                tm.addRow(o);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Data Tidak Ada");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        detilmuzaki = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        dEmas = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        dBersih = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        dTabungan = new javax.swing.JLabel();
        dLogam = new javax.swing.JLabel();
        dSurat = new javax.swing.JLabel();
        dProperti = new javax.swing.JLabel();
        dKendaraan = new javax.swing.JLabel();
        dKoleksi = new javax.swing.JLabel();
        dDagang = new javax.swing.JLabel();
        dLain = new javax.swing.JLabel();
        dPiutang = new javax.swing.JLabel();
        dHarta = new javax.swing.JLabel();
        dTempo = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        dJumlah = new javax.swing.JLabel();
        kembali = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        telp = new javax.swing.JTextField();
        nama = new javax.swing.JLabel();
        idzakat = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        detilmuzaki.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id_zakat", "NAMA", "NO TELP", "ALAMAT", "EMAIL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        detilmuzaki.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                detilmuzakiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(detilmuzaki);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("DETAIL DATA MUZAKI");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        dEmas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dEmas.setText("0");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Harga Emas");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Penghasilan Bersih");

        dBersih.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dBersih.setText("0");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel26.setText("Harta jatuh tempo");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("Harta surat");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setText("Harta Stock dagang");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Harta Logam");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setText("Harta Lainnya");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("Harta properti");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setText("Harta Koleksi");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("Harta kendaraan");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Harta Tabungan");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setText("Harta piutang lancar");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel25.setText("Jumlah Harta");

        dTabungan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dTabungan.setText("0");

        dLogam.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dLogam.setText("0");

        dSurat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dSurat.setText("0");

        dProperti.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dProperti.setText("0");

        dKendaraan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dKendaraan.setText("0");

        dKoleksi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dKoleksi.setText("0");

        dDagang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dDagang.setText("0");

        dLain.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dLain.setText("0");

        dPiutang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dPiutang.setText("0");

        dHarta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dHarta.setText("0");

        dTempo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dTempo.setText("0");

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel40.setText("Jumlah Perbulan");

        dJumlah.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dJumlah.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel40)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dJumlah))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel26))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(dTabungan)
                                    .addComponent(dEmas)
                                    .addComponent(dLogam)
                                    .addComponent(dSurat)
                                    .addComponent(dProperti)
                                    .addComponent(dKendaraan)
                                    .addComponent(dKoleksi)
                                    .addComponent(dDagang)
                                    .addComponent(dLain)
                                    .addComponent(dPiutang)
                                    .addComponent(dHarta)
                                    .addComponent(dTempo))))
                        .addGap(56, 56, 56))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(325, 325, 325)
                        .addComponent(dBersih)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(43, 43, 43)
                    .addComponent(jLabel15)
                    .addContainerGap(282, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(dEmas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(dBersih))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(dTabungan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dLogam)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dSurat)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dProperti)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dKendaraan)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dKoleksi)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dDagang)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dLain)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dPiutang)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dHarta)
                    .addComponent(jLabel25))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dTempo)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(dJumlah))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(37, 37, 37)
                    .addComponent(jLabel15)
                    .addContainerGap(374, Short.MAX_VALUE)))
        );

        kembali.setText("Kembali");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });

        edit.setText("Edit");
        edit.setToolTipText("");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        jLabel2.setText("Nama");

        jLabel3.setText("Nomer Telepon");

        jLabel4.setText("Alamat");

        jLabel5.setText("Email");

        nama.setText("....");

        idzakat.setText("....");

        jLabel6.setText("ID ZAKAT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idzakat, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(telp, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(196, 196, 196)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(151, 151, 151))))
            .addGroup(layout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(idzakat, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nama)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(telp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     
    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        // TODO add your handling code here:
        new formBayarZakat().setVisible(true);
        dispose();
    }//GEN-LAST:event_kembaliActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost/dompet_zakat", USER, PASS);
            stmt = conn.createStatement();
            String sql ="UPDATE muzaki SET no_telepon = '"+telp.getText()+"', alamat = '"+alamat.getText()+"',email= '"+email.getText()+"' WHERE nama_muzaki = '"+nama.getText()+"'";
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "data berhasil di edit");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Perubahan Data Gagal"+e.getMessage());
        }
        tampil();
        idzakat.setText(null);
        nama.setText(null);
        telp.setText(null);
        alamat.setText(null);
        email.setText(null);  
    }//GEN-LAST:event_editActionPerformed
    
    private int idZakatHarta;
    
    private void detilmuzakiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_detilmuzakiMouseClicked
        // TODO add your handling code here:
        int baris = detilmuzaki.rowAtPoint(evt.getPoint());
//        int dId = detilmuzaki.getValueAt(baris, 0);
        String sid = detilmuzaki.getValueAt(baris, 0).toString();
        idzakat.setText(sid);
        String snama =detilmuzaki.getValueAt(baris, 1).toString();
        nama.setText(snama);
        String stelp = detilmuzaki.getValueAt(baris,2).toString();
        telp.setText(stelp);
        String salamat =detilmuzaki.getValueAt(baris, 3).toString();
        alamat.setText(salamat);
        String semail = detilmuzaki.getValueAt(baris,4).toString();
        email.setText(semail);
        int dId = Integer.valueOf(sid);
                
         try{
            String select = "SELECT `harta_tab`, `harta_logam`, `harta_surat`, `harta_properti`, `harta_kendaraan`, `harta_koleksi`, `harta_stock_dagang`, `harta_lainnya`, `harta_piutang_lancar`, `jumlah_harta`, `harta_jatuh_tempo`, `zakat_harta`.`penghasilan_bersih`, `zakat_harta`.`zakat_pertahun`, `zakat_harta`.`zakat_perbulan`, `transaksi_zakat`.`harga_emas`\n" +
            "FROM `zakat_harta` \n" +
            "INNER JOIN `transaksi_zakat` ON (`transaksi_zakat`.`id_zakat` = `zakat_harta`.`id`)\n" +
            "WHERE `zakat_harta`.`id` = "+dId+"";
            java.sql.Connection conn=(Connection)Config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet rs=stm.executeQuery(select);
            while(rs.next()){
                double hartaTab = rs.getDouble("harta_tab");
                double hartaLogam = rs.getDouble("harta_logam");
                double hartaSurat = rs.getDouble("harta_surat");
                double hartaProp = rs.getDouble("harta_properti");
                double hartaKendaraan = rs.getDouble("harta_kendaraan");
                double hartaKoleksi = rs.getDouble("harta_koleksi");
                double hartaStock = rs.getDouble("harta_stock_dagang");
                double hartaLain = rs.getDouble("harta_lainnya");
                double hartaPiutang = rs.getDouble("harta_piutang_lancar");
                double jmlHarta = rs.getDouble("jumlah_harta");
                double hartaTempo = rs.getDouble("harta_jatuh_tempo");
                double pengBersih = rs.getDouble("penghasilan_bersih");
                double zPertahun = rs.getDouble("zakat_pertahun");
                double zPerbulan = rs.getDouble("zakat_perbulan");
                double hargaEmas = rs.getDouble("harga_emas");
                dTabungan.setText(String.valueOf(hartaTab));
                dLogam.setText(String.valueOf(hartaLogam));
                dSurat.setText(String.valueOf(hartaSurat));
                dProperti.setText(String.valueOf(hartaProp));
                dKendaraan.setText(String.valueOf(hartaKendaraan));
                dKoleksi.setText(String.valueOf(hartaKoleksi));
                dDagang.setText(String.valueOf(hartaStock));
                dLain.setText(String.valueOf(hartaLain));
                dPiutang.setText(String.valueOf(hartaPiutang));
                dHarta.setText(String.valueOf(jmlHarta));
                dTempo.setText(String.valueOf(hartaTempo));
                dBersih.setText(String.valueOf(pengBersih));
                dJumlah.setText(String.valueOf(zPerbulan));
                dEmas.setText(String.valueOf(hargaEmas));
            }
        } catch (Exception e){
           System.out.println("Data yang di select salah"); 
        }      
    }//GEN-LAST:event_detilmuzakiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(detildata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(detildata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(detildata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(detildata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new detildata().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JLabel dBersih;
    private javax.swing.JLabel dDagang;
    private javax.swing.JLabel dEmas;
    private javax.swing.JLabel dHarta;
    private javax.swing.JLabel dJumlah;
    private javax.swing.JLabel dKendaraan;
    private javax.swing.JLabel dKoleksi;
    private javax.swing.JLabel dLain;
    private javax.swing.JLabel dLogam;
    private javax.swing.JLabel dPiutang;
    private javax.swing.JLabel dProperti;
    private javax.swing.JLabel dSurat;
    private javax.swing.JLabel dTabungan;
    private javax.swing.JLabel dTempo;
    private javax.swing.JTable detilmuzaki;
    private javax.swing.JButton edit;
    private javax.swing.JTextField email;
    private javax.swing.JLabel idzakat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kembali;
    private javax.swing.JLabel nama;
    private javax.swing.JTextField telp;
    // End of variables declaration//GEN-END:variables
}
